# TIP: To edit secret files, run `nix run nixpkgs#sops -- secrets/secrets.yaml`
keys:
  # cat /etc/ssh/ssh_host_ed25519_key.pub | nix run nixpkgs#ssh-to-age
  # gpg --list-public-keys --with-colons | grep fpr | awk -F: '{print $10}' | head -n1
  - &openpgp 9C635181306E1D7FEA53858775DB252683B07650
  - &Proteus-NUC age1mfs3eh0zwpxse06x5dwg78rp3wmpxe8ag3yvkwmkkgrx7gpea96qglanyz
  - &Proteus-MBP14M4P age1g550pxhfzh6rtj76t6v7dzyrzy02g0kuqz27adml8eq7zw6l4adqvx4pm5
  - &Proteus-Desktop age1yv5rv2s3pgc0pxy03c560lz746s9r2qp3exzqq5m3equ5yjtsexscja2r9
  - &Proteus-NixOS-0 age125zqqjhess357kqc556n8zy7da6tq9hxnn85yzynuhdxlxljhveqcv7gjh
  - &Proteus-NixOS-1 age14peangqx8cc42grlrffkj9n6dvjqp4zkmdxppsh9d5nx5j96256smhsgdn
  - &Proteus-NixOS-2 age1xsge7vg6qnschk94pzymd5dk4q2ymcl5xx55aeeg8y78n0dja4fsdnz4wp
  - &Proteus-NixOS-3 age1slgumaq7nsda23q8rmml96fr56462gsjx5pcvp954y0zf92hksdsgtp6e6
  - &Proteus-NixOS-4 age1ktvdkyckex6pzprkxfutgeqhdygxfw6fl75fcntd8wzqpf8mgpuq7mk4l8
  - &Proteus-NixOS-5 age1yp5ep6qsw6k3sp9lzr890f4zqfjdeg3k2jqrmdr70vumen9kr4ashjyks6
# TIP: To rotate a encrypted file with new recipients
# updatekeys secrets/syncthing_proteus-nuc.priv.pem.age
# TIP:Use recovery key if lost access to secret keys
# SOPS_AGE_KEY=$(nix run nixpkgs#ssh-to-age -- -private-key -i ~/path/to/recovery.priv.key)
# To encrypt file:
# cat <file> | sops encrypt --filename-override secrets/<file>.sops --output secrets/<file>.sops
creation_rules:
  ## BEGIN Common
  - path_regex: secrets/common\.sops\.yaml$
    key_groups:
      - pgp: [*openpgp]
        age:
          - *Proteus-NUC
          - *Proteus-MBP14M4P
          - *Proteus-Desktop
          - *Proteus-NixOS-0
          - *Proteus-NixOS-1
          - *Proteus-NixOS-2
          - *Proteus-NixOS-3
          - *Proteus-NixOS-4
          - *Proteus-NixOS-5
  - path_regex: secrets/proteus_server\.priv\.pem\.sops$
    key_groups:
      - pgp: [*openpgp]
        age:
          - *Proteus-NUC
          - *Proteus-MBP14M4P
          - *Proteus-Desktop
          - *Proteus-NixOS-0
          - *Proteus-NixOS-1
          - *Proteus-NixOS-2
          - *Proteus-NixOS-3
          - *Proteus-NixOS-4
          - *Proteus-NixOS-5
  - path_regex: secrets/sb_test\.json\.sops$
    key_groups: [{ pgp: [*openpgp], age: [*Proteus-NUC, *Proteus-MBP14M4P] }]
  ## END Common
  ## BEGIN GCP Compute Engines
  ## END GCP Compute Engines
  ## BEGIN Proteus-NUC
  - path_regex: secrets/Proteus-NUC\.sops\.yaml$
    key_groups: [{ pgp: [*openpgp], age: [*Proteus-NUC] }]
  - path_regex: secrets/secureboot_PK\.key\.sops$
    key_groups: [{ pgp: [*openpgp], age: [*Proteus-NUC] }]
  - path_regex: secrets/secureboot_KEK\.key\.sops$
    key_groups: [{ pgp: [*openpgp], age: [*Proteus-NUC] }]
  - path_regex: secrets/secureboot_db\.key\.sops$
    key_groups: [{ pgp: [*openpgp], age: [*Proteus-NUC] }]
  ## END Proteus-NixOS
  ## BEGIN Proteus-MBP14M4P
  ## END Proteus-MBP14M4P
  ## BEGIN Proteus-Desktop
  - path_regex: secrets/authelia_oidc_rsa\.pem.sops$
    key_groups: [{ pgp: [*openpgp], age: [*Proteus-Desktop] }]
  - path_regex: secrets/Proteus-Desktop\.sops\.yaml$
    key_groups: [{ pgp: [*openpgp], age: [*Proteus-Desktop] }]
  - path_regex: secrets/Proteus-Desktop_syncthing\.priv\.pem\.sops$
    key_groups: [{ pgp: [*openpgp], age: [*Proteus-Desktop] }]
  ## END Proteus-Desktop
  ## BEGIN Trusted Machines (HM)
  # NOTE: for user secrets host ssh key cannot be accessed by a regular user
  - path_regex: secrets/nix_secret\.key\.sops$
    key_groups: [{ pgp: [*openpgp], age: [*Proteus-Desktop] }]
  - path_regex: secrets/common_hm\.sops\.yaml$
    key_groups: [{ pgp: [*openpgp], age: [*Proteus-Desktop] }]
  ## END Trusted Machines (HM)
  ## BEGIN Proteus-NUC (HM)
  # TIP: Encrypt in-place since sops matches inputs files for `path_regex`
  # sops encrypt -i secrets/syncthing_proteus-nuc.priv.pem.age
  # TIP: To edit, run
  # SOPS_AGE_KEY=$(nix run nixpkgs#ssh-to-age -- -private-key -i ~/Secrets/Backup/proteus@agenix-recovery.ssh.priv.key) sops -- edit secrets/syncthing_proteus-nuc.priv.pem.age
  - path_regex: secrets/Proteus-NUC_syncthing\.priv\.pem\.sops$
    key_groups: [pgp: [*openpgp]]
  - path_regex: secrets/gcloud_project-0\.secret\.json\.sops$
    key_groups: [pgp: [*openpgp]]
  - path_regex: secrets/gcloud_project-1\.secret\.json\.sops$
    key_groups: [pgp: [*openpgp]]
  - path_regex: secrets/gcloud_project-2\.secret\.json\.sops$
    key_groups: [pgp: [*openpgp]]
  ## END Proteus-NUC (HM)
  ## BEGIN Proteus-MBP14M4P (HM)
  # Encrypt in-place since sops matches inputs files for `path_regex`
  # sops encrypt -i secrets/syncthing_proteus-nuc.priv.pem.age
  # To edit, run
  # SOPS_AGE_KEY=$(nix run nixpkgs#ssh-to-age -- -private-key -i ~/Secrets/Backup/proteus@agenix-recovery.ssh.priv.key) sops -- edit secrets/syncthing_proteus-nuc.priv.pem.age
  - path_regex: secrets/Proteus-MBP14M4P_syncthing\.priv\.pem\.sops$
    key_groups: [pgp: [*openpgp]]
## END Proteus-MBP14M4P (HM)
