{
  config,
  lib,
  mylib,
  myvars,
  ...
}: let
  server_pub_crt = "${myvars.secrets_dir}/proteus_server.pub.pem";
in {
  networking.firewall = {
    allowedTCPPorts = [
      80 # Traefik
      443 # Traefik
      636 # OpenLDAP (secure)
    ];
    allowedUDPPorts = [
      443 # Traefik (QUIC)
      # 636 # OpenLDAP (secure, generally not used)
    ];
  };
  sops.secrets."traefik_server.priv.pem" = {
    sopsFile = "${myvars.secrets_dir}/proteus_server.priv.pem.sops";
    format = "binary";
    owner = config.systemd.services.traefik.serviceConfig.User;
    restartUnits = ["traefik.service"];
  };
  services.traefik = {
    enable = true;
    # Static configuration handles entrypoints (ports) and global settings
    staticConfigOptions = {
      global = {
        checkNewVersion = false;
        sendAnonymousUsage = false;
      };
      api.dashboard = true;
      entryPoints = {
        # Force HTTP to HTTPS redirect globally
        web = {
          address = ":80";
          http.redirections.entryPoint = {
            to = "websecure";
            scheme = "https";
          };
        };
        websecure = {
          address = ":443";
          http3 = {}; # For QUIC
          # Prevent large video uploads from timing out and throwing Error 499. Ref:
          # https://web.archive.org/web/20260217103328/https://docs.immich.app/administration/reverse-proxy/#traefik-proxy-example-config
          transport.respondingTimeouts = {
            readTimeout = "600s";
            idleTimeout = "600s";
          };
          # Allow IPs to ensure X-Forwarded-* headers (like X-Forwarded-Method) generated by Traefik on other nodes (e.g., Proteus-Desktop) are preserved and not dropped for security reasons.
          forwardedHeaders.trustedIPs =
            (lib.concatMap (iface: lib.optional (iface ? ipv4) iface.ipv4) myvars.networking.hosts_addr.Proteus-Desktop)
            ++ (lib.concatMap (iface: lib.optional (iface ? ipv6) iface.ipv6) myvars.networking.hosts_addr.Proteus-Desktop);
        };
        ldaps.address = ":636"; # Dedicated entrypoint for secure LDAP traffic
      };
    };
    # Dynamic configuration defines routing rules, backend services, and certificate management.
    dynamicConfigOptions = {
      # Establish the default fallback certificate.
      # This is critical for TCP clients (like `ldapsearch`) that do not send
      # Server Name Indication (SNI) data during the TLS handshake. Without this,
      # Traefik serves an untrusted dummy certificate.
      tls.stores.default.defaultCertificate = {
        certFile = server_pub_crt;
        keyFile = config.sops.secrets."traefik_server.priv.pem".path;
      };
      # For other domains
      # tls.certificates = [{certFile = server_pub_crt; keyFile = config.sops.secrets."traefik_server.priv.pem".path;}];
      http = {
        # For sunshine-webui
        serversTransports.ignorecert.insecureSkipVerify = true;
        routers = {
          traefik-dashboard = {
            rule = "Host(`traefik.${myvars.domain}`)";
            # `authelia-auth` Protect the dashboard
            entryPoints = ["websecure"];
            middlewares = ["authelia-auth"];
            service = "api@internal";
            tls = {};
          };
          qinglong = {
            rule = "Host(`ql.${myvars.domain}`)";
            entryPoints = ["websecure"];
            service = "qinglong";
            tls = {};
          };
          sb = {
            rule = "Host(`sb.${myvars.domain}`)";
            entryPoints = ["websecure"];
            middlewares = ["authelia-auth"];
            service = "sb-dashboard";
            tls = {};
          };
          syncthing = {
            rule = "Host(`syncthing.${myvars.domain}`)";
            entryPoints = ["websecure"];
            middlewares = ["authelia-auth"];
            service = "syncthing-dashboard";
            tls = {};
          };
          home-assistant = {
            rule = "Host(`hass.${myvars.domain}`)";
            entryPoints = ["websecure"];
            service = "home-assistant";
            tls = {};
          };
          sunshine-webui = {
            rule = "Host(`sunshine.${myvars.domain}`)";
            entryPoints = ["websecure"];
            service = "sunshine-webui";
            tls = {};
          };
          papra = {
            rule = "Host(`papra.${myvars.domain}`)";
            entryPoints = ["websecure"];
            service = "papra";
            tls = {};
          };
          notebook = {
            rule = "Host(`notebook.${myvars.domain}`)";
            entryPoints = ["websecure"];
            service = "notebook";
            tls = {};
          };
          forgejo = {
            rule = "Host(`git.${myvars.domain}`)";
            entryPoints = ["websecure"];
            service = "forgejo";
            tls = {};
          };
          plane = {
            rule = "Host(`plane.${myvars.domain}`)";
            entryPoints = ["websecure"];
            service = "plane";
            tls = {};
          };
        };
        services = {
          qinglong.loadBalancer.servers = [{url = "http://127.0.0.1:5700";}];
          sb-dashboard.loadBalancer.servers = [{url = "http://127.0.0.1:9091";}];
          syncthing-dashboard.loadBalancer = {
            # By setting to false Traefik will overrides the Host header to
            # 127.0.0.1
            passHostHeader = false;
            servers = [{url = "http://${config.home-manager.users.${myvars.username}.services.syncthing.guiAddress}";}];
            healthCheck.path = "/rest/noauth/health";
          };
          home-assistant.loadBalancer.servers = let
            hass_port = toString config.services.home-assistant.config.http.server_port;
          in [{url = "http://127.0.0.1:${hass_port}";} {url = "http://[::1]:${hass_port}";}];
          sunshine-webui.loadBalancer = {
            serversTransport = "ignorecert";
            servers = [{url = "https://127.0.0.1:${toString (config.services.sunshine.settings.port + 1)}";}];
          };
          papra.loadBalancer.servers = [{url = "http://127.0.0.1:1221";}];
          notebook.loadBalancer.servers = [
            {
              url = let
                find_first_infix = key: set:
                  builtins.elemAt
                  (lib.attrNames set)
                  (lib.lists.findFirstIndex (i: lib.hasInfix key i) null (lib.attrNames set));
                port =
                  toString (mylib.get_uri_port
                    (find_first_infix "notebook.${myvars.domain}" config.services.caddy.virtualHosts));
              in "http://127.0.0.1:${port}";
            }
          ];
          forgejo.loadBalancer = {
            servers = [
              {url = "http://127.0.0.1:${toString config.services.forgejo.settings.server.HTTP_PORT}";}
            ];
            healthCheck.path = "/api/healthz";
          };
          plane.loadBalancer.servers = [{url = "http://127.0.0.1:8081";}];
        };
      };
      tcp = {
        routers = {
          # Catch-all for traffic on this port. standard LDAP clients (like ldapsearch and many older legacy systems) do
          # not send SNI data.
          openldap-secure = {
            rule = "HostSNI(`*`)";
            entryPoints = ["ldaps"];
            service = "openldap-backend";
            tls = {};
          };
        };
        services.openldap-backend.loadBalancer = {
          proxyProtocol.version = 2; # Instruct Traefik to inject the PROXY protocol v2 header
          servers = let
            openldap_port = toString (mylib.get_uri_port (builtins.head config.services.openldap.urlList));
          in [{address = "127.0.0.1:${openldap_port}";} {address = "[::1]:${openldap_port}";}];
        };
      };
    };
  };
}
