{
  config,
  lib,
  myvars,
  ...
}: let
  server_pub_crt = "${myvars.secrets_dir}/proteus_server.pub.pem";
in {
  networking.firewall = {
    allowedTCPPorts = [80 443];
    allowedUDPPorts = [443]; # QUIC
  };
  sops.secrets."traefik_server.priv.pem" = {
    sopsFile = "${myvars.secrets_dir}/proteus_server.priv.pem.sops";
    format = "binary";
    owner = config.systemd.services.traefik.serviceConfig.User;
    restartUnits = ["traefik.service"];
  };
  services.traefik = {
    enable = true;
    # Static configuration handles entrypoints (ports) and global settings
    staticConfigOptions = {
      global = {
        checkNewVersion = false;
        sendAnonymousUsage = false;
      };
      api.dashboard = true;
      entryPoints = {
        # Force HTTP to HTTPS redirect globally
        web = {
          address = ":80";
          http.redirections.entryPoint = {
            to = "websecure";
            scheme = "https";
          };
        };
        websecure = {
          address = ":443";
          http3 = {}; # For QUIC
          # Prevent large video uploads from timing out and throwing Error 499. Ref:
          # https://web.archive.org/web/20260217103328/https://docs.immich.app/administration/reverse-proxy/#traefik-proxy-example-config
          transport.respondingTimeouts = {
            readTimeout = "600s";
            idleTimeout = "600s";
          };
          # Allow IPs to ensure X-Forwarded-* headers (like X-Forwarded-Method) generated by Traefik on other nodes (e.g., Proteus-Desktop) are preserved and not dropped for security reasons.
          forwardedHeaders.trustedIPs =
            (lib.concatMap (iface: lib.optional (iface ? ipv4) iface.ipv4) myvars.networking.hosts_addr.Proteus-Desktop)
            ++ (lib.concatMap (iface: lib.optional (iface ? ipv6) iface.ipv6) myvars.networking.hosts_addr.Proteus-Desktop);
        };
      };
    };
    # Dynamic configuration defines routing rules, backend services, and certificate management.
    dynamicConfigOptions = {
      # Establish the default fallback certificate.
      # This is critical for TCP clients (like `ldapsearch`) that do not send Server Name Indication (SNI) data during
      # the TLS handshake. Without this, Traefik serves an untrusted dummy certificate.
      tls.stores.default.defaultCertificate = {
        certFile = server_pub_crt;
        keyFile = config.sops.secrets."traefik_server.priv.pem".path;
      };
      # For other domains
      # tls.certificates = [{certFile = server_pub_crt; keyFile = config.sops.secrets."traefik_server.priv.pem".path;}];
      http = {
        routers = {
          traefik-dashboard = {
            rule = "Host(`traefik.${myvars.domain}`)";
            # `authelia-auth` Protect the dashboard
            entryPoints = ["websecure"];
            middlewares = ["authelia-auth"];
            service = "api@internal";
            tls = {};
          };
          qinglong = {
            rule = "Host(`ql.${myvars.domain}`)";
            entryPoints = ["websecure"];
            service = "qinglong";
            tls = {};
          };
          syncthing = {
            rule = "Host(`syncthing.${myvars.domain}`)";
            entryPoints = ["websecure"];
            middlewares = ["authelia-auth"];
            service = "syncthing-dashboard";
            tls = {};
          };
          sb = {
            rule = "Host(`sb.${myvars.domain}`)";
            entryPoints = ["websecure"];
            middlewares = ["authelia-auth"];
            service = "sb-dashboard";
            tls = {};
          };
          papra = {
            rule = "Host(`papra.${myvars.domain}`)";
            entryPoints = ["websecure"];
            service = "papra";
            tls = {};
          };
          plane = {
            rule = "Host(`plane.${myvars.domain}`)";
            entryPoints = ["websecure"];
            service = "plane";
            tls = {};
          };
        };
        services = {
          qinglong.loadBalancer.servers = [{url = "http://127.0.0.1:5700";}];
          sb-dashboard.loadBalancer.servers = [{url = "http://127.0.0.1:9091";}];
          syncthing-dashboard.loadBalancer = {
            # By setting to false Traefik will overrides the Host header to
            # 127.0.0.1
            passHostHeader = false;
            servers = [{url = "http://${config.home-manager.users.${myvars.username}.services.syncthing.guiAddress}";}];
            healthCheck.path = "/rest/noauth/health";
          };
          papra.loadBalancer.servers = [{url = "http://127.0.0.1:1221";}];
          plane.loadBalancer.servers = [{url = "http://127.0.0.1:8081";}];
        };
      };
    };
  };
}
