{ lib, mylib }:
{
  ## BEGIN pkgs agnostic variables
  username = "proteus";
  userFullName = "Proteus Qian";
  email = "sudaku233@outlook.com";
  nixosStateVersion = "26.05";
  darwinStateVersion = 7;
  githubUsername = "magic0whi";
  secretsDir = mylib.relativeToRoot "secrets";

  latitude = "31.3113626";
  longitude = "121.5020943";
  timeZone = "Asia/Hong_Kong"; # Main timezone

  domain = "proteus.eu.org";
  tailnet = "tailba6c3f.ts.net";
  networking = import ./networking.nix { inherit lib; };
  # Initial Hashed Password is used for the first-run only, as I use OpenLDAP to manage cross-OS autnenticate
  # Generated by `mkpasswd -m scrypt`
  # initial_hashed_password = "$7$CU..../....ok6SfTAfNaBUnQ96VKt.Y.$e6xJ04cp782zzn07DNj7PtvteiEbpzKyeWibpkQIXX.";
  # Public Keys that can be used to login to all my PCs, Macbooks, and servers.
  #
  # Since its authority is so large, we must strengthen its security:
  # 1. The corresponding private key must be:
  #    1. Generated locally on every trusted client via:
  #      ```bash
  #      # KDF: bcrypt with 256 rounds, takes 2s on Apple M2):
  #      # Passphrase: digits + letters + symbols, 12+ chars
  #      ssh-keygen -t ed25519 -a 256 -C "ryan@xxx" -f ~/.ssh/xxx`
  #      ```
  #    2. Never leave the device and never sent over the network.
  # 2. Or just use hardware security keys like Yubikey/CanoKey.
  sshAuthorizedKeys = [
    "ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIHBAm5d2IeApyfv8zLb7IMpex7wVHkCV86ztON7HFTkn openpgp:0xB17F9ED3"
  ];
  gitSigningKey = "73EDF7A727CC3B5F329863DBFC4881A7361DF34E";
  # Use an [A]uthenticate subkey, run `gpg --list-secret-keys --with-keygrip` to show its keygrip
  gpgKeygrip = [ "94BDB192359497927D5AA4AC76D238BA1BFEFE57" ];

  catppuccin = {
    flavor = "mocha";
    accent = "pink";
  };

  storagePath = "/mnt/storage/data";

  backupTimes = {
    forgejo = "02:00:00";
    paperless = "02:15:00";
    postgresql = "02:20:00";
  };

  base = {
    nixpkgs_modules = map mylib.relativeToRoot [
      "modules/secrets"

      # "modules/common/default.nix"
      "modules/common/easytier.nix"
      # "modules/common/fonts.nix"
      "modules/common/misc.nix"
      "modules/common/nix.nix"
      # "modules/common/packages.nix"
      "modules/common/shell.nix"
      # "modules/common/ssh.nix"
      "modules/common/tailscale.nix"

      # "modules/nixos_headless/default.nix"
      # "modules/nixos_headless/fhs.nix"
      "modules/nixos_headless/firewall.nix"
      # "modules/nixos_headless/fonts.nix"
      "modules/nixos_headless/impermanence.nix"
      # "modules/nixos_headless/krnl-compat.nix"
      "modules/nixos_headless/misc.nix"
      "modules/nixos_headless/niks3-auto-upload.nix"
      # "modules/nixos_headless/packages.nix"
      # "modules/nixos_headless/power-mgmt.nix"
      # "modules/nixos_headless/remote-build.nix"
      "modules/nixos_headless/scx-loader.nix"
      # "modules/nixos_headless/secureboot.nix"
      "modules/nixos_headless/sssd.nix"
      "modules/nixos_headless/systemd-resolved.nix"
      "modules/nixos_headless/traffic-quota.nix"
      # "modules/nixos_headless/zfs.nix"
    ];
  };
  ## END pkgs agnostic functions
  ## BEGIN pkgs dependent variables
  mkForPkgs = pkgs: {
    monospace = {
      name = "Iosevka Nerd Font Mono";
      package = pkgs.nerd-fonts.iosevka;
    };
  };
  ## END pkgs dependent variables
}
