{
  config,
  lib,
  const,
  pkgs,
  ...
}:
{
  ## BEGIN Session Manager
  programs.noctalia-greeter = {
    enable = true;
    package = pkgs.noctalia-greeter;

    # Optional configuration
    greeter-args = "";
    settings.cursor =
      let
        cfg = config.home-manager.users.${const.username}.home.pointerCursor;
      in
      {
        theme = cfg.name;
        inherit (cfg) size package;
      };
  };
  services = {
    displayManager.sessionPackages =
      let
        my_sessions =
          let
            hm_session =
              let
                name = "hm-session.desktop";
              in
              pkgs.writeTextFile {
                inherit name;
                destination = "/share/wayland-sessions/${name}";
                # `.wayland-session` is a script generated by home-manager, which links to the current wayland compositor
                # (hyprland or others). With such a vendor-no-locking script, we can switch to another wayland compositor
                # without modifying Greetd's config here.
                text = ''
                  [Desktop Entry]
                  Name=Home Manager Session
                  Exec=sh -c "\$HOME/.wayland-session"
                  Type=Application
                '';
              };
            steam_custom =
              let
                name = "steam-custom.desktop";
              in
              pkgs.writeTextFile {
                inherit name;
                destination = "/share/wayland-sessions/${name}";
                text = ''
                  [Desktop Entry]
                  Name=Steam (Gamescope)
                  Exec=${lib.getExe config.programs.gamescope.package} -W 1920 -H 1080 -f -e --xwayland-count 2 --hdr-enabled --hdr-itm-enabled -- steam -pipewire-dmabuf -gamepadui -steamdeck -steamos3
                  Type=Application
                '';
              };
          in
          pkgs.symlinkJoin {
            name = "custom-greetd-sessions";
            paths = [
              hm_session
              steam_custom
            ];
            passthru.providedSessions = [
              "hm-session"
              "steam-custom"
            ];
          };
      in
      [ my_sessions ];
    # https://wiki.archlinux.org/title/Greetd
    greetd = {
      enable = true;
      settings = {
        default_session = lib.mkMerge [
          (lib.mkIf (!config.programs.noctalia-greeter.enable) {
            command = lib.mkDefault "${pkgs.tuigreet}/bin/tuigreet --time --remember --remember-session";
          })
          { user = const.username; } # Wayland Desktop Manager is installed only for user
        ];
      };
    };
  };
  ## END Session Manager
  ## BEGIN xdg.nix
  xdg.portal = {
    enable = true;
    wlr.enable = true;
    extraPortals = [
      pkgs.xdg-desktop-portal-gtk
      pkgs.xdg-desktop-portal-hyprland # Screensharing, put this on home manager will not take effect
    ];

    config.common.default = [ "gtk" ]; # Use xdg-desktop-portal-gtk for every portal interface
  };
  ## END xdg.nix
  ## BEGIN security.nix
  # Security with gnome-kering
  services.gnome.gnome-keyring.enable = lib.mkDefault true;
  security.pam.services.greetd.enableGnomeKeyring = true;
  # Secret portal is handled by gnome-keyring
  xdg.portal.config.common."org.freedesktop.impl.portal.Secret" = [ "gnome-keyring" ];
  ## END security.nix
  ## BEGIN misc.nix
  programs.dconf.enable = true;
  services = {
    gvfs.enable = true; # Mount, trash, and other functionalities
    tumbler.enable = true; # Thumbnail support for images
  };
  ## END misc.nix
}
